dist: xenial

language: python

matrix:
  include:
    - env: TOX_ENV='py27-django111-{locmem,file,memcached,redis_cache,django_redis}'
      python: "2.7"
    - env: TOX_ENV='py36-django{21,22,30,31,32}-{locmem,file,memcached,redis_cache,django_redis}'
      python: "3.6"
    - env: TOX_ENV='py37-django{21,22,30,31,32}-{locmem,file,memcached,redis_cache,django_redis}'
      python: "3.7"
    - env: TOX_ENV='py38-django{21,22,30,31,32}-{locmem,file,memcached,redis_cache,django_redis}'
      python: "3.8"
    - env: TOX_ENV='py39-django{30,31,32}-{locmem,file,memcached,redis_cache,django_redis}'
      python: "3.9"

install:
  - pip install tox

script: tox . -e $TOX_ENV

services:
  - redis-server
  - memcached